# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

install! 'cocoapods', :deterministic_uuids => false

target 'ContactCenterMessagingApp' do
  use_frameworks!
  pod 'AdaptiveCards'
  
  # update latest ContactCenterMessagingSDK version
  $sdkVersion = 'v1.1.1'
  pod 'ContactCenterMessagingSDK', :podspec => 'https://github.com/microsoft/ContactCenterMessagingSDK-ios/releases/download/' + $sdkVersion + '/ContactCenterMessagingSDK-ios.podspec'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end
end
end
